### ISSUE TITLE
ToDo in prevalidation script

### ISSUE THREAD

**Issue by SebastianKerger** [rhaberme/hsg_data_validation#1]
Adding more tests:
- [ ] accuracy test: If the uncertainty is too high
- [ ] Z-test for outliers
- [ ] Grubbs test
- [ ] Cook’s distance
Adding a comparison:
- [ ] create new script in which we combine the hand written anomlies and the anomlies from the prevalidation scripts
- [ ] Create an evaluation which anomalies can be detected and which cant
